question_data = [{"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                                   "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "FLAC stands for Free Lossless Audio Condenser'",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "DragonForce's 'Through the Fire and Flames' is widely considered to be the hardest song in the Guitar Hero series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "The Gympie Stinger is the deadliest plant in the world.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "In 2016, the United Kingdom voted to stay in the EU.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Type 1 diabetes is a result of the liver working improperly.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                  "question": "Studio Ghibli is a Japanese animation studio responsible for the films Wolf Children and The Boy and the Beast.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The first Metal Gear game was released for the PlayStation 1.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The word news originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                                    "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The color orange is named after the fruit.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                                    "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game's plot.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The French word to travel is Travail", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                   "question": "Toronto is the capital city of the North American country of Canada.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
                  "question": "The Pepe meme originated from a comic drawn by Matt Furie called Boy's Club?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
                  "question": "Cube, Cube 2: Hypercube and Cube Zero were directed by the same person.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The Battle of Trafalgar took place on October 23rd, 1805", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "E = MC3",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Oxford University is older than the Aztec Empire. ", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "Stevie Wonder's real name is Stevland Hardaway Morris.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "Scatman John's real name was John Paul Larkin.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
                  "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
                  "question": "In the To Love-Ru series, Peke is considered a female robot.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Return to Castle Wolfenstein was the only game of the Wolfenstein series where you don't play as William B.J. Blazkowicz.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The majority of Subaru vehicles are made in China.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                                   "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                  "question": "The movie Tron received an Oscar nomination for Best Visual Effects.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
                  "question": "The singer Billie Holiday was also known as Lady Day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "In Minecraft, gold tools are faster than diamond tools.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Neutral Milk Hotel is a real band.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Shang Tsung is a playable character in Mortal Kombat XL.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "medium",
                                                   "question": "Franz Joseph I was the last emperor of Austria.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Musicals & Theatres", "type": "boolean", "difficulty": "hard",
                  "question": "The protagonist's names in Who's Afraid of Virginia Woolf, George and Martha, were derived from George Washington and his wife.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
